spring:
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:renlm/ConfigRepo.git
          forcePull: true
          cloneOnStart: false
          defaultLabel: master
          search-paths: config/{profile}
          ignoreLocalSshSettings: true
          passphrase: ${GIT_PASSPHRASE:ICgacH955iKjdfu8idh^988jErQ63moj3Uy54r}
          privateKey: |-
            -----BEGIN RSA PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,A2CAA05969CC28DCC4789726FF6DBB4A
            
            U3RrrKMVIF8L2HqPvIdZnZ8avlHMNuJGOwpxGRDTRLKeodVL881tD0VlJ+7XNWGC
            oAPV7fQPi8mTP929HskNzYDy3FhwcQ7Id2gUhhA8IqwzccgTPjLTS9qgNnJ6GQBT
            vIeZJKTLnEtedadGLneRYFXreZMDoH9Y28N5KdkvyUokKsaNr3wkP/PEJ/EJOxG3
            WKDOLDo2wYGqFa2ipmqTJfhcBJsKJfkOm0nBmMPMloutNnDfvtbt1+a39QqSZ4rW
            3E/LqQHMULJH7bPvRI1032g9pNfi8glZ+fezGF2G1YkamlbjxSEj9z25gZUu9Dtv
            Z0tebWT2FRwdLwqmOaNQagRL3gLPjwhO8z91Cnr1iY3G2OigN5ehyXdF2Lt9xGfw
            6FfBQSbwq7QMdMo1flXQV7fXB4O209b0tRNKM6wiZxMqyUjX7z+6xjBFIqbdpHYa
            nv8TFgpL4cbrkCXZ6lZWoPVc5NRUE59awyo99AWAWrw4mWJcd7tbtV7NPecB52T4
            9ZOdEiABkrZ8KgIxRIPxgJqEYRh7HuNRaXMODXEggtkwOZ1xLw9AO5BSQLJPADIv
            2yfQ0xuon13lcpRqmG8NpbTNMi7bQ3KEeHcyi7EtNqOijY1ndXNqHm83qL2HE+wr
            ZKgmlNsnZG3icSY6qEcanBnI/e8TEHg3g1/jE8eIEF+A4GIsEpTtNyvYHysAeayz
            kYLG5esI6pB/4zv1sXNNTVhFzkmmuhbwILlFeHUkpy/AzrSmA1JgRGTPDXY4l+JP
            QWjWVSGRYLzfBJGbR30ScxuVz3U0kpRcQ8n6pSNrBMtLzvPYsJIU1HZJgiJBDjSz
            EgStkr+NgZryNvr0tKf/wM3dkbE8F5xrego807rpAm9GSEW51v/4Cyl0I/2mkUmh
            h4nZ2pwVdpVawfUmI5rtQPW51rzR+WJS9LONUGl/yzRFz3KoQlGZe15lAtQX9wGl
            /9M390xRrAkg2skA1UtG13yYfkAliRpJ+8qL8XyTzz31whAvJjdoI6uXESV1It8f
            G7pxzKZ4BL+NYCFETeuBFR61xIOXONy6AI9EEePOGuoW4PD9SjUIph08902DA6Eh
            y3k5oOvE6AXIduTBUFnlssU+1SAlZso3kqrc/OUSHdQN8dj35G2FQsS/rVqeU2gh
            Zi+8hQRrWprk9/AQL73KCGlRuHgJy4K73czTf5hNZyffP6Oea5NGf+8ltAq22q9r
            6DqO8N2ThK8vfTpg5vQw5jraM+Yfdi1HJTJLiqZIlXuTZn/gqsaW7sMzY3+Nc57w
            ne2+0xPten2ffzDP625Cf4aZVCLtmv/3BX6AQfIjaazbeaNrxEwMlBUIhF09TaxT
            Svzf50Efa6VbJgq4nSOw8NE5KAEqOag7QNznGNqDYUwAMVX+60noFGBRrFXJkgNk
            8CsckqBIkgYJkC+8JI+6h958FV7pzSd9HQQYFpkPY1E7YYVhQSPZxte2c8YiEJHi
            p0+i00BLqOHHY2UAhCoVORDnEdimvX7eh9OXZsnTFSDV/3pd3Z4vskH7UlmTCGP9
            sdCl3uZ27euK0BA9mBM/LLg6nhhsZkiIw9MWViZNFwrtcEtP8q4ruvT5d/buD6zp
            -----END RSA PRIVATE KEY-----